"""Add stream Model

Revision ID: 1dae8e5ca82c
Revises: 345d032527ec
Create Date: 2026-03-31 17:12:47.544922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dae8e5ca82c'
down_revision: Union[str, Sequence[str], None] = '345d032527ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_mtx_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('path_name', sa.Enum('ORIGINAL', 'ANALYSIS', name='streamtype'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['media_mtx_id'], ['media_mtx.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_name')
    )
    op.create_index(op.f('ix_stream_id'), 'stream', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_id'), table_name='stream')
    op.drop_table('stream')
    # ### end Alembic commands ###
