"""revision mediaMtx Model add name, rtsp,hls,webrtc port

Revision ID: 345d032527ec
Revises: 6dbf06eb8569
Create Date: 2026-03-31 16:48:46.428780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345d032527ec'
down_revision: Union[str, Sequence[str], None] = '6dbf06eb8569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_mtx', sa.Column('name', sa.String(), nullable=True))
    op.add_column('media_mtx', sa.Column('rtsp_port', sa.Integer(), nullable=True))
    op.add_column('media_mtx', sa.Column('hls_port', sa.Integer(), nullable=True))
    op.add_column('media_mtx', sa.Column('webrtc_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_mtx', 'webrtc_port')
    op.drop_column('media_mtx', 'hls_port')
    op.drop_column('media_mtx', 'rtsp_port')
    op.drop_column('media_mtx', 'name')
    # ### end Alembic commands ###
