"""Revision Stream model

Revision ID: 59b0c3993028
Revises: 5c3bf6e28727
Create Date: 2026-04-07 17:57:15.979679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b0c3993028'
down_revision: Union[str, Sequence[str], None] = '5c3bf6e28727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stream_path_name_key'), 'stream', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('stream_path_name_key'), 'stream', ['path_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
