"""Revision Camera Model

Revision ID: 5c3bf6e28727
Revises: f4008c5b2fee
Create Date: 2026-04-01 11:11:14.625196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c3bf6e28727'
down_revision: Union[str, Sequence[str], None] = 'f4008c5b2fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'uuid',
               existing_type=sa.VARCHAR(),
               type_=postgresql.UUID(as_uuid=True),
                postgresql_using='uuid::uuid',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'uuid',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
