"""revision mediaMtx Model table name

Revision ID: 6dbf06eb8569
Revises: b50623db4b5d
Create Date: 2026-03-31 16:38:31.997766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbf06eb8569'
down_revision: Union[str, Sequence[str], None] = 'b50623db4b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_mtx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_index(op.f('ix_media_mtx_id'), 'media_mtx', ['id'], unique=False)
    op.drop_index(op.f('ix_mediaMtx_id'), table_name='mediaMtx')
    op.drop_table('mediaMtx')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediaMtx',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mediaMtx_pkey')),
    sa.UniqueConstraint('ip', name=op.f('mediaMtx_ip_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mediaMtx_id'), 'mediaMtx', ['id'], unique=False)
    op.drop_index(op.f('ix_media_mtx_id'), table_name='media_mtx')
    op.drop_table('media_mtx')
    # ### end Alembic commands ###
