"""Add mediaMtx Model

Revision ID: b50623db4b5d
Revises: ea2bb95800d9
Create Date: 2026-03-31 16:36:38.007896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50623db4b5d'
down_revision: Union[str, Sequence[str], None] = 'ea2bb95800d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediaMtx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_index(op.f('ix_mediaMtx_id'), 'mediaMtx', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mediaMtx_id'), table_name='mediaMtx')
    op.drop_table('mediaMtx')
    # ### end Alembic commands ###
