"""Revision media mtx model add api_port

Revision ID: d0ee9f69b03d
Revises: 1dae8e5ca82c
Create Date: 2026-03-31 17:25:09.759276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ee9f69b03d'
down_revision: Union[str, Sequence[str], None] = '1dae8e5ca82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_mtx', sa.Column('api_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_mtx', 'api_port')
    # ### end Alembic commands ###
