"""revision camera_model code to uuid

Revision ID: ea2bb95800d9
Revises: 6aa8ff920275
Create Date: 2026-03-31 15:12:32.489669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2bb95800d9'
down_revision: Union[str, Sequence[str], None] = '6aa8ff920275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('uuid', sa.String(), nullable=False))
    op.drop_constraint(op.f('cameras_code_key'), 'cameras', type_='unique')
    op.create_unique_constraint(None, 'cameras', ['uuid'])
    op.drop_column('cameras', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cameras', type_='unique')
    op.create_unique_constraint(op.f('cameras_code_key'), 'cameras', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('cameras', 'uuid')
    # ### end Alembic commands ###
